services:
  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    networks:
      - local-network

  # for detail, see https://medium.com/@katyagorshkova/docker-compose-for-running-kafka-in-kraft-mode-20c535c48b1a
  kafka-gen:
    image: apache/kafka:3.8.0
    hostname: kafka-gen
    container_name: kafka-gen
    volumes:
      - /Users/dereckchen/code/graduate/remagen/docker/scripts/create_cluster_id.sh:/tmp/create_cluster_id.sh
      - /Users/dereckchen/code/graduate/remagen/docker/clusterID:/tmp/clusterID
    command: "bash -c '/tmp/create_cluster_id.sh'"

  kafka1:
    image: apache/kafka:3.8.0
    hostname: kafka1
    container_name: kafka1
    environment:
      NEED_CREATE_TOPICS: "true" # 由kafka1来创建topics
    ports:
      - "9092:9092"
      - "8848:8848"
    volumes:
      - /Users/dereckchen/code/graduate/remagen/docker/config/server1.properties:/opt/kafka/config/kraft/server.properties
      - /Users/dereckchen/code/graduate/remagen/docker/config/connect-distributed1.properties:/opt/kafka/config/connect-distributed.properties
      - /Users/dereckchen/code/graduate/remagen/docker/clusterID:/tmp/clusterID
      - /Users/dereckchen/code/graduate/remagen/docker/scripts/update_run.sh:/tmp/update_run.sh
      - /Users/dereckchen/code/graduate/remagen/docker/libs/remagen-connect-1.0-SNAPSHOT.jar:/opt/kafka/libs/remagen-connect-1.0-SNAPSHOT.jar
    networks:
      - local-network
    command: "bash -c '/tmp/update_run.sh'"


  kafka2:
    image: apache/kafka:3.8.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9092"
      - "8849:8848"
    volumes:
      - /Users/dereckchen/code/graduate/remagen/docker/config/server2.properties:/opt/kafka/config/kraft/server.properties
      - /Users/dereckchen/code/graduate/remagen/docker/config/connect-distributed2.properties:/opt/kafka/config/connect-distributed.properties
      - /Users/dereckchen/code/graduate/remagen/docker/clusterID:/tmp/clusterID
      - /Users/dereckchen/code/graduate/remagen/docker/scripts/update_run.sh:/tmp/update_run.sh
      - /Users/dereckchen/code/graduate/remagen/docker/libs/remagen-connect-1.0-SNAPSHOT.jar:/opt/kafka/libs/remagen-connect-1.0-SNAPSHOT.jar
    networks:
      - local-network
    command: "bash -c '/tmp/update_run.sh'"


  kafka3:
    image: apache/kafka:3.8.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9092"
      - "8850:8848"
    volumes:
      - /Users/dereckchen/code/graduate/remagen/docker/config/server3.properties:/opt/kafka/config/kraft/server.properties
      - /Users/dereckchen/code/graduate/remagen/docker/config/connect-distributed3.properties:/opt/kafka/config/connect-distributed.properties
      - /Users/dereckchen/code/graduate/remagen/docker/clusterID:/tmp/clusterID
      - /Users/dereckchen/code/graduate/remagen/docker/scripts/update_run.sh:/tmp/update_run.sh
      - /Users/dereckchen/code/graduate/remagen/docker/libs/remagen-connect-1.0-SNAPSHOT.jar:/opt/kafka/libs/remagen-connect-1.0-SNAPSHOT.jar
    networks:
      - local-network
    command: "bash -c '/tmp/update_run.sh'"


networks:
  local-network:
    driver: bridge